# Generated by Django 4.1.5 on 2023-05-30 12:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appMy', '0002_productstok_images'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productstok',
            old_name='size',
            new_name='sizeletter',
        ),
    ]
