# Generated by Django 4.1.5 on 2023-05-30 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appMy', '0005_product_colors'),
    ]

    operations = [
        migrations.AddField(
            model_name='color',
            name='styletitle',
            field=models.CharField(max_length=50, null=True, verbose_name='Renk style'),
        ),
    ]
